# Generated by Django 3.2.7 on 2021-09-13 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Faculties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Факультеты',
                'verbose_name_plural': 'Факултеты',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Группа')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.departments', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.departments', verbose_name='Кафедра')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.faculties', verbose_name='Факультет')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.groups', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Студенты',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.CreateModel(
            name='Obhodnoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(verbose_name='Дата рождения')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('statusLibrary', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус библиотеки')),
                ('statusInternationalDepartment', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус международного отдела')),
                ('passportPhoto', models.FileField(upload_to='photos/%Y/%m/%d/', verbose_name='Фотография паспорта')),
                ('statusPassporttiska', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус паспортистки')),
                ('statusKafedra', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус кафедры')),
                ('statusAccounting', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус бухгалтерии')),
                ('statusDormitories', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус общежитии')),
                ('statusStudentOK', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус студенческого отдела кадров')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('document', models.CharField(choices=[('В обработке', 'В обработке'), ('Завершен', 'Завершен'), ('Отклонён', 'Отклонён')], default='В обработке', max_length=30, verbose_name='Статус документа')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='docs.students', verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Обходной лист',
                'verbose_name_plural': 'Обходные листы',
                'ordering': ['-time_create'],
            },
        ),
        migrations.AddField(
            model_name='departments',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='docs.faculties', verbose_name='Факультет'),
        ),
    ]
